import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
    title: "Chat app",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.svg"
    }
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <link rel="icon" href="/favicon.ico" sizes="any" />
                <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
                <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
                <link rel="manifest" href="/manifest.json" />
                <meta name="msapplication-TileColor" content="#4285f4" />
                <meta name="theme-color" content="#4285f4" />
            </head>
            <body>{children}</body>
        </html>
    )
}
